// <auto-generated />
using DiAndSignalRApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiAndSignalRApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211123093247_AddPkInStudent")]
    partial class AddPkInStudent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiAndSignalRApp.Models.Guardian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("DiAndSignalRApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DiAndSignalRApp.Models.Student", b =>
                {
                    b.Property<int>("GuardianOneId")
                        .HasColumnType("int");

                    b.Property<int>("GuardianTwoId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuardianOneId", "GuardianTwoId");

                    b.HasIndex("GuardianTwoId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DiAndSignalRApp.Models.Student", b =>
                {
                    b.HasOne("DiAndSignalRApp.Models.Guardian", "GuardianOne")
                        .WithMany("StudentsForGuardianOne")
                        .HasForeignKey("GuardianOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiAndSignalRApp.Models.Guardian", "GuardianTwo")
                        .WithMany("StudentsForGuardianTwo")
                        .HasForeignKey("GuardianTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GuardianOne");

                    b.Navigation("GuardianTwo");
                });

            modelBuilder.Entity("DiAndSignalRApp.Models.Guardian", b =>
                {
                    b.Navigation("StudentsForGuardianOne");

                    b.Navigation("StudentsForGuardianTwo");
                });
#pragma warning restore 612, 618
        }
    }
}
